MBS-11017: Clean up IMSLP to HTTPS and add validation
metabrainz/musicbrainz-server pull request #1635
Opened 2020-08-06 16:03 UTC by reosarevok

### Implement MBS-11017

2020-09-08 11:30 UTC, reosarevok commented
I modified the test to check for cleanup. I'm not sure about how to further test for validation with our current test setup, since score already applies only to work and imslp to artist :)

2020-09-08 15:49 UTC, yvanzo requested changes
LGTM but error message being returned even though validation has been successful.

Also, I updated ticket’s description, please update commit message/pull request too.

2020-09-08 15:49 UTC, yvanzo commented on root/static/scripts/edit/URLCleanup.js
> +          };
Successful validation should not set error message.

2020-09-08 15:49 UTC, yvanzo commented on root/static/scripts/edit/URLCleanup.js
> +          };
Same as above.

2020-09-10 14:27 UTC, yvanzo approved these changes
LGTM but commit message

2020-09-16 17:56 UTC, mwiencek approved these changes

2020-09-16 18:08 UTC, merged