MBS-8668: Block adding duplicates to a series
metabrainz/musicbrainz-server pull request #1659
Opened 2020-08-20 06:21 UTC by reosarevok

### Fix MBS-8668

Elsewhere, we accept relationships as different if their link order varies. For series though, unless the number attribute is different, we probably don't want to have the same entity listed many times (and to the user is often not obvious at all that a link order even exists, especially if the series is set to automated order).

WIP: this does block the duplicates but causes unexpected side effects because of throwing DuplicateViolation (see image below). This should ideally also be dealt with by the relationship editor, rather than only blocked on the Perl layer. Putting it up anyway because I will forget I worked on it otherwise and because maybe I can get some suggestions on how to improve it :) 

Do we consider it safe to ignore link order for PART_OF_SERIES, or are there cases where this does matter?

![Screenshot from 2020-08-19 15-48-18](https://user-images.githubusercontent.com/1069224/90723999-70acdb80-e2c6-11ea-9cb8-b05ac2f52787.png)

2020-09-16 07:50 UTC, yvanzo requested changes
I guess the DuplicateViolation was intended for newly created duplicate entity, not for duplicate relationship. It seems worth to have two distinct errors then.

Pre-existing duplicates should probably not block editing a series, just like we intentionally don’t block editing an entity if an existing URL relationship is not valid anymore.

The check should still be made on the back-end as data validation is one of its main purposes.

2021-05-20 14:00 UTC, mwiencek commented on lib/MusicBrainz/Server/Data/Relationship.pm
> +    if ($values->{link_order} && !$ignore_link_order) {
Should check `defined` to handle 0, right? Or `non_empty`
```suggestion
    if (defined $values->{link_order} && !$ignore_link_order) {
```

2021-05-20 14:00 UTC, mwiencek commented on root/static/scripts/relationship-editor/common/entity.js
> +                        var obj = _.omit(rel.editData(), "id");
```suggestion
                        const obj = _.omit(rel.editData(), "id");
```

2021-05-20 18:13 UTC, reosarevok commented on lib/MusicBrainz/Server/Data/Relationship.pm
> +    my $ignore_link_order = grep { $_ eq $values->{link_type_gid} } values %PART_OF_SERIES;
Those are only done with arrows though, so you can't get a duplicate order, can you?

2023-01-16 10:44 UTC, reosarevok commented
Testing this with the new relationship editor, the JS part is no longer needed because the new editor already detects these as duplicates and blocks them.

The Perl part might be worth keeping in case the JS check fails / gets bypassed.

For some reason, the exception message is not being shown anymore though - in fact `/series/476798b7-12ae-4237-9e2f-e2d4d6fab5f2` (with a duplicate release of catno 469 202-2) does not show any error message at all when trying to edit it.

2023-02-10 05:41 UTC, mwiencek commented
> Testing this with the new relationship editor, the JS part is no longer needed because the new editor already detects these as duplicates and blocks them.

I can still add duplicates without any UI error in the beta branch, but only one duplicate per entity (same as MBS-12838 describes).

1. Add a new part to any automatic series, with a number set (from the series edit page)
2. Submit the edit
3. Reload the series edit page and add the exact same relationship with the same number attributes
4. It lets you submit the edit

If I try to repeat steps 3 & 4 again, it doesn't let me (it finally detects the new relationship as a duplicate of the previous two, somehow).

So it seems like some UI changes must be needed still.

2023-02-10 09:04 UTC, reosarevok commented
Hmm, ok, I guess I was just testing adding the same rel twice, but not adding an existing rel :) I'll look into it.

2025-03-04 14:43 UTC, reosarevok commented on lib/MusicBrainz/Server/Data/Relationship.pm
> +    my $ignore_link_order = grep { $_ eq $values->{link_type_gid} } values %PART_OF_SERIES;
> "stuff like recording-recording compilation/DJ-mix relationships probably make sense to ignore too"

Actually if the same recording is used twice in a DJ-mix or whatnot, that would seem legit - maybe better to stick to series only when ignoring link orders.

2025-04-01 00:27 UTC, mwiencek commented on lib/MusicBrainz/Server/Data/Relationship.pm
> +    my $ignore_link_order = grep { $_ eq $values->{link_type_gid} } values %PART_OF_SERIES;
I see you pass `link_type_gid` to here in two places below, but if I search for `model('Relationship')->exists`, there are 5 calls (including one in the tests). So it seems kinda unclear whether it's required. Would it make sense to just add a constant for the part-of-series row IDs instead, so that a gid isn't needed?

2025-04-01 08:37 UTC, reosarevok commented on lib/MusicBrainz/Server/Data/Relationship.pm
> +    my $ignore_link_order = grep { $_ eq $values->{link_type_gid} } values %PART_OF_SERIES;
You mean just use `link_type_id` and have something like `@PART_OF_SERIES_ROW_IDS` that we look at instead? If that seems better, I can do that.

I'm confused about the "So it seems kinda unclear whether it's required" bit - if what is required? :) We need to look at this in here in some way to avoid a `MusicBrainz::Server::Edit::Exceptions::NoChanges->throw`, I understand.

2025-04-01 08:51 UTC, reosarevok commented on lib/MusicBrainz/Server/Data/Relationship.pm
> +    my $ignore_link_order = grep { $_ eq $values->{link_type_gid} } values %PART_OF_SERIES;
Seems we don't use the Perl `%PART_OF_SERIES` anywhere else, not sure if it should in that case be removed or what :)

2025-04-01 09:06 UTC, reosarevok commented on lib/MusicBrainz/Server/Data/Relationship.pm
> +    my $ignore_link_order = grep { $_ eq $values->{link_type_gid} } values %PART_OF_SERIES;
I pushed a commit changing to use row ids - tested quickly by disabling the JS check, seems to work fine.

2025-04-01 15:10 UTC, mwiencek commented on lib/MusicBrainz/Server/Data/Relationship.pm
> +    my $ignore_link_order = grep { $_ eq $values->{link_type_gid} } values %PART_OF_SERIES;
> I'm confused about the "So it seems kinda unclear whether it's required" bit - if what is required? :) We need to look at this in here in some way to avoid a MusicBrainz::Server::Edit::Exceptions::NoChanges->throw, I understand.

I meant whether the `link_type_gid` was required, since you weren't passing it in all cases. (For example, maybe because the places it wasn't being passed never dealt with series relationships.) But I prefer we always perform this check (hence switching to the row IDs).

Now I'm a bit confused: isn't this patch intended to cause *more* `NoChanges` exceptions to be thrown? (Since `NoChanges` == this is a duplicate.)

2025-04-01 15:27 UTC, mwiencek reviewed
This looks good to me overall, though it's kinda subtle behavior so it seems like the kind of thing that should have at least one test on the Perl and JS side:
 * We have an existing test for "Don't consider relationships with different link orders to be the same" in t/lib/t/MusicBrainz/Server/Data/Relationship.pm which we could copy and adapt for the series case.
 * On the JS side we have a "compareRelationships: Series comparisons" test in root/static/scripts/tests/relationship-editor/utility/compareRelationships.js which we could just amend with one additional case.

2025-04-01 15:27 UTC, mwiencek commented on lib/MusicBrainz/Server/Data/Relationship.pm
> +    my $ignore_link_order = grep { $_ eq $values->{link_type_id} } values %PART_OF_SERIES_ROW_IDS;
Should we just store them as a list like `PART_OF_SERIES_LINK_TYPE_IDS` in root/static/scripts/common/constants.js so that we don't need to convert it via `values`? (At least until we have a use for looking them up by entity type.) I guess we could also use `contains_number` from `Data::Utils`, then. :)

2025-04-02 12:59 UTC, reosarevok commented on lib/MusicBrainz/Server/Data/Relationship.pm
> +    my $ignore_link_order = grep { $_ eq $values->{link_type_id} } values %PART_OF_SERIES_ROW_IDS;
Oh, I didn't realize we were already doing it that way in JS. Then we might as well, sure.

2025-04-02 14:02 UTC, reosarevok commented
Added the suggested tests. Reworded the existing JS ones a bit since they were confusingly mentioning "order" when they meant "number" (so, "ordering attribute").

2025-04-02 16:54 UTC, mwiencek commented
It seems we're also lacking a JS check for the case where you edit an existing relationship to have the same number as another. The Perl still blocks the addition with a `NoChanges` exception, but there's otherwise no error message when the form is reloaded (with the dupe relationship still being visible).

Ideally the relationship dialog would block the edit to begin with. I guess the `!(isPartOfSeries && isAdd)` check should also include edits, though it will have the effect of blocking any edits to the relationship that don't also fix the dupe number, IIUC.

2025-04-03 23:00 UTC, merged