MBS-11139: Normalize to HTTPS on Library of Congress links
metabrainz/musicbrainz-server pull request #1727
Opened 2020-10-04 11:58 UTC by reosarevok

### Implement MBS-11139

LoC now redirects to HTTPS, so we should do too.

2020-10-04 11:59 UTC, mwiencek approved these changes

2020-10-07 09:43 UTC, yvanzo approved these changes
This was not really needed but if you do so you should update existing links to `https` so as to preserve normalization (which helps with searching for URL and preventing duplicate).

2020-10-07 12:35 UTC, reosarevok commented
I think it does make sense (we should try to always use https when possible) but agreed on the normalization - entered MBBE-16 for that. I'm going to try to set up a bot for MBBE this week, that seems like a good start issue.

2020-10-07 13:13 UTC, yvanzo requested changes
I just reminded why these URLs are being enforce to `http` over `https`: it’s what is used by the Library of Congress itself.

For example, all the links from http://id.loc.gov/authorities/names/n79146554 are still using `http` either because the page is outdated but more likely because it’s considered as a permalink more than a simple URI. The same goes for VIAF URLs. I guess we should keep the normalized `http` form in the database, and link using `https` in the webpage only, just like do for VIAF and some others already.

2020-10-07 14:12 UTC, reosarevok commented
Made the change.

2020-10-07 14:49 UTC, yvanzo approved these changes

2020-10-08 08:40 UTC, merged