MBS-11199: Remove superfluous 7digital parameters
metabrainz/musicbrainz-server pull request #1764
Opened 2020-10-22 06:49 UTC by reosarevok

### Implement MBS-11199

2020-10-22 07:18 UTC, yvanzo requested changes

2020-10-22 07:18 UTC, yvanzo commented on root/static/scripts/edit/URLCleanup.js
> +      url = url.replace(/([^&?]+)(?:.*)$/, '$1');
Just drop any fragment (can be tested with `#skip-back-to-top`) too with:

```suggestion
      url = url.replace(/([^&?#]+)(?:.*)$/, '$1');
```

2020-10-26 18:41 UTC, yvanzo approved these changes

2020-10-28 18:11 UTC, mwiencek approved these changes

2020-10-28 18:16 UTC, merged