MBS-11216: Split InstrumentsWithoutAnImage report
metabrainz/musicbrainz-server pull request #1786
Opened 2020-11-11 12:13 UTC by reosarevok

### Implement MBS-11216

Wikidata is not connected to images at all anymore, but it's still a very useful link to have. As such, it makes sense to split this report in two. Also changed the query a bit to hopefully improve it.

We could just remove InstrumentsWithoutAnImage, but hopefully we can soon use it again once we start being able to link to IROM images on StaticBrainz.

2020-11-12 15:14 UTC, mwiencek requested changes

2020-11-12 15:14 UTC, mwiencek commented on lib/MusicBrainz/Server/Report/InstrumentsWithoutAnImage.pm
> +            AND lt.gid = 'f64eacbd-1ea1-381e-9886-2cfb552b7d90' --wikidata
```suggestion
            AND lt.gid = 'f64eacbd-1ea1-381e-9886-2cfb552b7d90' --image
```

2020-11-18 19:03 UTC, mwiencek approved these changes

2020-11-18 20:15 UTC, yvanzo approved these changes

2020-11-18 20:22 UTC, merged