MBS-11292: Do not use UN flag for [Worldwide]
metabrainz/musicbrainz-server pull request #1836
Opened 2020-12-29 11:40 UTC by reosarevok

### Implement MBS-11292

As suggested in the ticket, that's not quite appropriate.

This uses a globe flag - sadly, it gets so distorted at this tiny size that it is hard to understand what's going on, but that was also completely true of the previous one.

2020-12-30 17:20 UTC, mwiencek approved these changes
Either image is unintelligible to me unless my nose touches the screen

2021-01-02 09:04 UTC, yvanzo requested changes
Its darkened blue color makes it less distinguishable from the European Union flag, which is even less representative. Ticket’s suggestion of either a visually similar icon (same color, different symbol) or a blue globe like the emoji would be a better fit.

2021-01-11 10:13 UTC, reosarevok commented
Updated with the flag pmepepnoute uploaded to Jira, does seem better.

2021-01-12 16:13 UTC, yvanzo approved these changes

2021-01-13 08:26 UTC, merged