MBS-11304: Add recordings’ first release date to artist/release lookup
metabrainz/musicbrainz-server pull request #1847
Opened 2021-01-04 12:31 UTC by reosarevok

### Implement MBS-11304

Release is needed for Picard. Artist just seems reasonable if we're adding the release one.

2021-01-05 08:19 UTC, yvanzo approved these changes
* Checked parity with search results (which just do not return recordings but at top level)
* Checked compatibility with/without active schema 26
* Updated ticket MBS-11304 accordingly

Note: `inc=recording-rels` is not affected.

2021-01-05 08:20 UTC, yvanzo commented
@reosarevok: It requires updating https://wiki.musicbrainz.org/MusicBrainz_API though.

2021-01-05 14:29 UTC, reosarevok commented
@yvanzo: you mean the examples at https://wiki.musicbrainz.org/MusicBrainz_API/Examples ? I don't see anywhere on the basic page that this would be mentioned :)

2021-01-05 14:51 UTC, yvanzo commented
Right, please link to the corresponding wiki diff(s).

2021-01-06 19:26 UTC, mwiencek requested changes
Mentioned this on IRC, but I'd prefer not adding it to /ws/2/artist/?inc=recordings if Picard doesn't need it. That feature is useless (since it returns a fixed list of 25 recordings by the artist) and supplanted by proper recording browse requests. Returning more information there might signal to people in the patch notes that they should actually be using that feature.

2021-01-06 19:26 UTC, mwiencek commented on t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
> +                                "first-release-date" => '2001-07-04',
```suggestion
                                "first-release-date" => '2001-07-04',
```

2021-01-06 21:19 UTC, reosarevok commented
Dropped it from artists then.

2021-01-06 21:26 UTC, reosarevok commented
Ok, removed it from artist then :)

2021-01-07 18:07 UTC, mwiencek approved these changes

2021-01-07 19:33 UTC, merged