MBS-11337: Prioritize link to URL page on URL reports
metabrainz/musicbrainz-server pull request #1869
Opened 2021-01-19 13:34 UTC by reosarevok

### Implement MBS-11337

On reports about URLs, it makes sense to prioritize the URL entity (since that's where you can fix the problems). It still makes sense to have a link to the actual destination though.

At the moment UrlRelationshipList showed URLs in the same way as elsewhere on the site (destination link on click + [info] link to the entity) while the other lists being changed here only linked to the entity but did not allow following the link. This standardises both of these to the format "link to url entity [follow link]", which prioritizes the entity but allows doing both things.

2021-01-19 17:54 UTC, yvanzo approved these changes
Code looks good to me but did not test, approving that. However, the issue itself doesn’t seem to be an improvement to me. Were you unhappy with consistency?

2021-01-20 06:08 UTC, reosarevok commented
Well, there's two things: one is the inconsistency (we showed the URLs in two different ways in different reports). The other is that in a report about a URL entity, the URL entity itself should be prioritized, not the external link, because that is what the report is about. The Discogs reports understood this (but were missing a way to follow the actual link, which can sometimes also be useful). The DeprecatedRels report did not, so the link to go to the actual place where you can do something about the issue was an insignificant amount of the report's visual space :) It's not like we don't already have cases where a URL links to the entity - apart from the Discogs reports, we also do it on the URL page headers (https://musicbrainz.org/url/8c23ed7f-e0dc-4e19-8e5a-9c18212a96a1)

2021-01-26 04:40 UTC, mwiencek commented
This seems weird to me since clicking [info] like everywhere else isn't difficult, but anyway: what do you think about adding a separate component for this instead of another flag to `EntityLink`? That component is already a bit messy and over-broad.

2021-01-26 07:05 UTC, reosarevok commented
> clicking [info] like everywhere else isn't difficult

Say you want to open the first 10 URL pages in a report fast. Since [info] is at the end of the URL, there's no consistent place for it, so you can't just quickly go down the lines and click, you have to stop, see where it is, go and click each time. With the change, you can click the same place (the start of the line) quickly. Another option, if you feel that's better, would be to put the URL entity link in a second column, but that still wouldn't help with the inconsistent Discogs links :)

2021-01-26 07:38 UTC, yvanzo requested changes
Finally, it seems I’m not the only one to think it’s weird, maybe because it is.

> On reports about URLs, it makes sense to prioritize the URL entity (since that's where you can fix the problems). It still makes sense to have a link to the actual destination though.

It makes little sense to have a linked name after an URL that points to a different URL.

Please avoid doing that. Instead, the actual URL could be preceded with a link named after the entity’s MBID. That would probably be more intuitive.

2021-01-26 07:51 UTC, reosarevok commented
> It makes little sense to have a link named after an URL that points to a different URL. Please avoid doing that 

Should we also be changing the URL entity headers then? And if so, what to?

2021-01-26 08:25 UTC, yvanzo commented
Or possibly two columns “MusicBrainz URL” and “External link”?

2021-01-26 13:12 UTC, reosarevok commented
> Or possibly two columns “MusicBrainz URL” and “External link”?

As I answered to @mwiencek earlier: 
> Another option, if you feel that's better, would be to put the URL entity link in a second column, but that still wouldn't help with the inconsistent Discogs links :)

Since those are just one header (and only link to the URL entity right now, see https://musicbrainz.org/report/DiscogsLinksWithMultipleArtists). I always feel it's a bit silly to have a column that's literally the text "See URL entity" or something repeated on every line, but if that feels better to you I can live with that :)

2021-01-26 13:51 UTC, yvanzo commented
About naming a link with another link, `DiscogsLinksWithMultipleArtists` seems to be an exception that should probably not last. If you don’t feel comfortable with making two columns, just make one. There is no need to change the column headers either, “URL” is just fine.

2021-01-27 00:53 UTC, mwiencek commented
> Say you want to open the first 10 URL pages in a report fast. Since [info] is at the end of the URL, there's no consistent place for it, so you can't just quickly go down the lines and click, you have to stop, see where it is, go and click each time.

Good point. I just thought it was weird to use a URL as link text and not have it go to that same URL, & make it inconsistent with the [info] display everywhere else. But clearly the [info] stuff isn't great for reports.

> I always feel it's a bit silly to have a column that's literally the text "See URL entity" or something repeated on every line

We could use the literal entity URL (`https://musicbrainz.org/url/...`), or just the MBID as the link text. Not opposed to "See URL entity" either, even if it looks dumb. It's not much different from "follow link" except those don't vertically align.

2021-03-25 16:43 UTC, yvanzo approved these changes
Works for me (after deprecating BBC relationships in sample data). Thanks!

2021-05-28 06:32 UTC, mwiencek approved these changes

2021-05-31 12:16 UTC, merged