MBS-11346: Lower duration threshold on dubious duration discID report
metabrainz/musicbrainz-server pull request #1875
Opened 2021-01-23 00:52 UTC by loujine

Implement MBS-11346

The report (discIDs durations > 100 minutes) is now empty, Setting to 88 minutes to get more results and avoid too many false positive.

2021-01-23 08:16 UTC, yvanzo reviewed
Thanks @loujine!

90 minutes CD-R and even 100 minutes CD-R are quite common. Should the query be updated to exclude CD-R such as https://musicbrainz.org/cdtoc/ttC8YktpxuooF3AKLYsgp7Pt5A0- too? Maybe some other formats are to be excluded too?

2021-01-25 00:18 UTC, loujine commented
@yvanzo : I'll still add another commit excluding CD-R. I don't know if you looked at https://loujine.github.io/musicbrainz-sql/2021-01-13/discid_above_90_minutes.html - FYI the CD-R you mention seems to be the only one > 86 minutes

I am realizing at the same time:
- I should have a different limit for 8cm mini-CD, probably ~25 minutes (we have 29 discids above this limit in the DB)
- there are a few disc IDs on vinyl, cassette... in the database. It might deserve another report

2021-01-25 06:59 UTC, yvanzo approved these changes
Even better!

2021-01-25 12:23 UTC, reosarevok requested changes
Please use format IDs, not names, for matching :) Names can change. Also, maybe leave a comment for the 8cm cutoff too?

Other than that this looks good :)

2021-01-26 00:34 UTC, loujine commented
@reosarevok : should be fixed

Thanks for the reviews!

2021-01-26 12:46 UTC, reosarevok approved these changes
Assuming those are the right IDs :)

2021-01-26 13:10 UTC, merged