MBS-10012: Treat http and https version of link as same for adding
metabrainz/musicbrainz-server pull request #1935
Opened 2021-02-25 11:48 UTC by reosarevok

### Implement MBS-10012

There's no reason I can see why we shouldn't block adding a http link if https exists already, and vice versa. I haven't seen any side effects of just making linkTypeAndUrlString normalize it.

Tested by both trying to add the two links from the ticket (http://www.example.com/path/object vs https://www.example.com/path/object) on artist creation and release creation, and by adding both to an artist (temporarily the code disallowing this) and then checking that they are detected as duplicates on loading the artist edit page once the code is changed back.

2021-02-27 08:59 UTC, yvanzo reviewed
A detrimental effect of this patch is that someone entering an `https` URL would see its addition being rejected even though the existing `http` URL might be obsolete. The error message would be no longer appropriate.
Made a comment to the ticket to see if we can use more context to better handle the most common case.

2021-03-01 21:05 UTC, reosarevok commented
FWIW, IIRC that shows "this relationship already exists" under both the new *and* the old link, so they could choose to remove (or update) the old link instead, I guess?

2021-03-08 04:28 UTC, mwiencek commented
That makes sense to me. If they know they `http` is obsolete and intend to replace it, they can just edit the existing URL.

2021-03-08 04:28 UTC, mwiencek approved these changes

2021-03-09 10:23 UTC, yvanzo requested changes
I tested by adding `http://www.nin.com/` first, then `https://www.nin.com/` to a release, it has not been detected as duplicate.

2021-03-09 11:05 UTC, yvanzo approved these changes
My bad, I did not recompile scripts before testing them.

I noticed another point: If an entity already has a pair of duplicate http/https links, it is not possible to edit that entity unless removing one of the links. It is probably not an issue here as it is very simple to drop one of the two links and it is not a big deal if a newcomer drops the https link instead of the http one.

2021-03-09 11:26 UTC, reosarevok commented
Added MBS-11429 for that issue (not so relevant here, I agree, but more relevant elsewhere).

2021-03-09 11:27 UTC, merged