MBS-9866: Add bubbles explaining what IPI and ISNI are on add forms
metabrainz/musicbrainz-server pull request #1942
Opened 2021-02-25 21:22 UTC by reosarevok

### Implement MBS-9866

It's hard to explain these in a very clear way, but really the most important thing here is to tell users that no, they really don't need to freak out about not being able to fill these.

2021-03-01 17:45 UTC, yvanzo approved these changes

2021-03-01 17:45 UTC, yvanzo commented on root/components/forms.tt
> +      <p>[% l('IPI codes are assigned by CISAC to "interested parties" in musical rights management.
```suggestion
      <p>[% l('IPI codes are assigned by CISAC to “interested parties” in musical rights management.
```

2021-03-03 01:35 UTC, mwiencek requested changes

2021-03-03 01:35 UTC, mwiencek commented on root/components/forms.tt
> +               Check {ipi_doc|the docs} for more info.',
```suggestion
               Check {ipi_doc|the documentation} for more info.',
```

2021-03-03 01:35 UTC, mwiencek commented on root/components/forms.tt
> +               Check {isni_doc|the docs} for more info.',
```suggestion
               Check {isni_doc|the documentation} for more info.',
```

2021-03-08 04:12 UTC, mwiencek approved these changes

2021-03-08 11:20 UTC, merged