MBS-11454: Don't consider hasTooEarlyFormat a blocking error
metabrainz/musicbrainz-server pull request #1992
Opened 2021-03-17 12:49 UTC by reosarevok

### Fix MBS-11454

The whole point of having `hasUnconfirmedEarlyFormat` was for that to be the one that triggers an error, while just `hasTooEarlyFormat` should not. Compare `hasUnconfirmedVariousArtists` vs `hasVariousArtists`.

2021-03-22 16:04 UTC, yvanzo requested changes
The code change looks good but the commit message is very unclear.

2021-03-22 17:49 UTC, reosarevok commented
What is unclear about it? :/

2021-03-22 18:50 UTC, yvanzo commented
@reosarevok: I reviewed code changes thanks to the ticket’s description. How could I suggest what is unclear to me? :D

2021-03-23 06:06 UTC, reosarevok commented
@yvanzo added some more text to the commit message, is it better now?

2021-03-23 17:44 UTC, yvanzo approved these changes
@reosarevok: Much better, thank you!

2021-03-24 15:53 UTC, mwiencek approved these changes

2021-03-24 18:01 UTC, merged