MBS-11476: Don't show own open edits in /edit/open
metabrainz/musicbrainz-server pull request #1995
Opened 2021-03-18 08:12 UTC by reosarevok

### Implement MBS-11476

We already filter edits the editor has voted on, so obviously this is meant for voting. As such, it is useless to show open edits by that specific editor.

2021-03-24 17:05 UTC, mwiencek requested changes

2021-03-24 17:05 UTC, mwiencek commented on lib/MusicBrainz/Server/Data/Edit.pm
> +            AND EDITOR != ?
No need to demonstrate that PG is case insensitive here. :)
```suggestion
            AND editor != ?
```

2021-03-24 17:30 UTC, mwiencek approved these changes

2021-03-29 09:52 UTC, yvanzo approved these changes
:ship:

2021-03-29 16:58 UTC, merged