MBS-10726: Use "medium", not "disc", as a generic term in RE buttons
metabrainz/musicbrainz-server pull request #2010
Opened 2021-03-22 14:39 UTC by reosarevok

### Implement MBS-10726

These can apply to mediums that are not discs. The pregap / data track strings only apply to actual discs, so not changing those for now.

2021-03-22 15:23 UTC, yvanzo commented
@brainzbot retest this please

2021-03-22 15:44 UTC, yvanzo requested changes
Please add a commit to rename misleading identifiers too.

2021-03-22 15:44 UTC, yvanzo commented on root/release/edit/tracklist.tt
> +          <button type="button" class="icon collapse-disc" data-click="toggleMedium" data-bind="css: { 'expand-disc': collapsed, 'collapse-disc': !collapsed() }, attr: { title: collapsed() ? '[% l('E
`collapse-disc`and `expand-disc` should probably be renamed too.

2021-03-22 15:44 UTC, yvanzo commented on root/release/edit/tracklist.tt
> +            <label data-bind="attr: { for: 'disc-title-' + uniqueID }">[% l('Medium title:') %]</label>
The same with `disc-title-<id>`.

2021-03-22 15:44 UTC, yvanzo commented on root/release/edit/tracklist.tt
> +          <button type="button" class="icon disc-up" title="[% l('Move medium up') %]" data-click="moveMediumUp"></button>
The same with `disc-down` and `disc-up`.

2021-03-22 17:50 UTC, reosarevok commented
I thought I wouldn't touch those to avoid making this bigger, but I guess it is unlikely to break anything (scripts or whatnot), so I can make the change :)

2021-03-23 06:21 UTC, reosarevok commented
I made the change, but properly then - I think I changed everything in the RE that should be medium but was disc :) Do let me know if you find something I missed.

2021-03-23 17:51 UTC, yvanzo approved these changes
Roughly tested with editing “The Downward Spiral” release from sample data: http://localhost:5000/release/0ce274e3-3b89-4d15-94ac-4f92e497ea60/edit

There are a few more occurrences of `disc` in code but that would be a much deeper change since we use it in URLs. Lasting occurrences can be changed later on.

2021-03-24 16:34 UTC, mwiencek commented on root/release/edit/tracklist.tt
> +    <li><a href="#add-medium-medium">[% l('Existing medium') %]</a></li>
> add-medium-medium

Maybe we should rename this to `add-medium-existing` or something else now :D

2021-03-24 17:53 UTC, mwiencek approved these changes

2021-03-24 18:22 UTC, merged