MBS-11564: Don't block Niconi Commons links with Nicovideo cleanup
metabrainz/musicbrainz-server pull request #2044
Opened 2021-04-07 08:59 UTC by reosarevok

### Fix MBS-11564

commons.nicovideo links are separate from the general nicovideo system and should not be autoselected as streamingfree (if they should be autoselected at all then probably as downloadfree, but that is an issue for a future PR). They also shouldn't be blocked, which is what the cleanup code was currently doing.
For now, this patch just makes the system ignore them so that they can be entered as needed.

2021-04-12 13:54 UTC, yvanzo requested changes
Please add a test with `expected_relationship_type: undefined`.

2021-04-12 15:50 UTC, reosarevok commented
Done :)

2021-04-12 16:48 UTC, yvanzo approved these changes
Thanks!

2021-04-14 16:37 UTC, mwiencek approved these changes

2021-04-14 17:18 UTC, merged