Fix catalyst warning: don't try to trim/sanitize undef "strings"
metabrainz/musicbrainz-server pull request #2064
Opened 2021-04-14 09:57 UTC by reosarevok

This causes warnings once it gets passed to NFC. If $t is empty, I expect there's no need to do any of the sanitizing / trimming anyway, so we might as well just return it unchanged.

This is triggered at least by _clean_link_attribute with no credit or text value, but looking at logs, I think it's triggered elsewhere too.

2021-04-14 16:57 UTC, mwiencek commented on lib/MusicBrainz/Server/ControllerUtils/Relationship.pm
> +    my $text_value = trim($data->{text_value}) if non_empty($data->{text_value});
No need for these changes if you're modifying `trim`, I guess?

2021-04-14 16:59 UTC, mwiencek commented
There's a test failure in `t::MusicBrainz::Server::Controller::URL::Edit`, can you check if it's valid?

2021-04-14 17:16 UTC, reosarevok commented
It's valid, fixed now. Turns out the sanitizing was turning undef into '', so changed it to do the same while skipping the sanitizing process.

2021-04-14 18:50 UTC, yvanzo requested changes
May the same error happen at some place where there is no test for it?

Some calls to `trim` do similar checks already, either before passing the argument, or after, or expect either `''` or `undef`. See for example:
* https://github.com/metabrainz/musicbrainz-server/blob/v-2021-04-05/lib/MusicBrainz/Server/Controller/ReleaseEditor.pm#L147-L149
* https://github.com/metabrainz/musicbrainz-server/blob/v-2021-04-05/lib/MusicBrainz/Server/Controller/ReleaseEditor.pm#L155-L157
* https://github.com/metabrainz/musicbrainz-server/blob/v-2021-04-05/lib/MusicBrainz/Server/Controller/ReleaseEditor.pm#L396

It seems unnecessary to keep the `// ''`when passing an argument to `trim`, that is easy to remove. But checking if returned values still work seems to require more investigation.

2021-04-14 18:52 UTC, reosarevok commented
Given I changed it to always return '' which seems to be what it was doing before, I doubt anything should break? But we could drop the // '' I guess, sure.

2021-04-14 20:16 UTC, mwiencek commented
The returned values were already `''` given `undef`:

```sh
$ rlwrap re.pl
push @INC, 'lib';
use MusicBrainz::Server::Data::Utils qw( sanitize trim trim_multiline_text );
defined trim(undef) && trim(undef) eq '';
Use of uninitialized value in subroutine entry at lib/MusicBrainz/Server/Data/Utils.pm line 333, <FIN> line 3.
Use of uninitialized value in subroutine entry at lib/MusicBrainz/Server/Data/Utils.pm line 333, <FIN> line 3.
1
defined trim_multiline_text(undef) && trim_multiline_text(undef) eq '';
Use of uninitialized value in subroutine entry at lib/MusicBrainz/Server/Data/Utils.pm line 368, <FIN> line 4.
Use of uninitialized value in subroutine entry at lib/MusicBrainz/Server/Data/Utils.pm line 368, <FIN> line 4.
1
defined sanitize(undef) && sanitize(undef) eq '';
Use of uninitialized value in subroutine entry at lib/MusicBrainz/Server/Data/Utils.pm line 333, <FIN> line 5.
Use of uninitialized value in subroutine entry at lib/MusicBrainz/Server/Data/Utils.pm line 333, <FIN> line 5.
1$
```

2021-04-21 17:48 UTC, yvanzo commented
Thanks for having checked. These `// ''` should still be removed though.

2021-04-27 19:42 UTC, yvanzo approved these changes
Thanks!

2021-04-27 19:45 UTC, mwiencek approved these changes

2021-04-27 19:46 UTC, merged