MBS-11638 / MBS-11639 / MBS-11640: Fixes for the work attribute form
metabrainz/musicbrainz-server pull request #2090
Opened 2021-05-05 11:57 UTC by reosarevok

### Fix MBS-11638 / MBS-11639 / MBS-11640

See commit messages for details

Tested manually by creating the relevant situations on local data.

2021-05-05 13:14 UTC, reosarevok commented on root/static/scripts/work.js
> +    }), this, 'beforeChange');
This causes an issue with our flow typing for subscribe - the typing needs to be updated to support these extra arguments, AFAICT. Not quite sure how to do so.

2021-05-20 12:44 UTC, mwiencek requested changes
Works well. I was thinking it'd make sense to prevent submission and show an error with JS, but that's kind of annoying with Knockout and this probably isn't a super common error, so it could wait.

2021-05-20 12:49 UTC, mwiencek commented on lib/MusicBrainz/Server/Form/Work.pm
> +        my @used_attribute_values = @{ $used_attributes{$attribute_type} // [] };
Try `//= []`, then you can remove the line `$used_attributes{$attribute_type} = \@used_attribute_values;` below.

2021-05-20 14:28 UTC, mwiencek approved these changes

2021-05-24 16:42 UTC, yvanzo reviewed
Commit about MBS-11638 works for me. I did not find how to reproduce MBS-11639. There is no mention of MBS-11640 in commits. (Reran CI test to make it pass.)

2021-05-24 16:50 UTC, reosarevok commented
@yvanzo: for MBS-11639 you can just pick "Key", select whatever value, then change the selection to one of the free text attributes (any of the identifiers). You should see the value ID for the previously selected key as the free text value (at least on Chrome). I seemingly squashed MBS-11640 into the MBS-11639 commit by mistake, will split.

2021-06-08 21:26 UTC, merged