MBS-6140: Allow (recording|work)-level-rels for release browse
metabrainz/musicbrainz-server pull request #2173
Opened 2021-07-16 09:16 UTC by reosarevok

### Implement MBS-6140

I can see no reason why we would prefer users to make one extra call per release rather than requesting this via browse when they need it. Recording already supports work-level-rels in browse, too, so this adds consistency.

Added tests too.

2021-08-12 12:48 UTC, reosarevok commented
@brainzbot, retest this please

2021-09-10 01:33 UTC, mwiencek commented
This should be fine since it still hits the `$max_recording_relationships` limit.  Can you add a test for `work-level-rels` too though?

2021-09-10 01:34 UTC, mwiencek commented on t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseRelease.pm
> +            <medium>
nitpick, but some of the indentation here is off (text-representation, cover-art-archive, medium-list, pregap, etc.)

2021-09-10 11:31 UTC, reosarevok commented
Added the test

2021-09-13 14:14 UTC, yvanzo requested changes
The code looks good, but the commit message doesn’t:

> I can see no reason why we would prefer users to make one extra call per release rather than requesting this via browse when they need it. Recording already supports work-level-rels

The reasons seem to be (have been) that some releases have so many tracks that it could cause load issues, and that extra calls are rate-limited. This can be overcome since the above-mentioned `$max_recording_relationships` is used. On the other hand, it will return 500 recordings at most.

> Recording already supports work-level-rels in browse, too, so this adds consistency.

Recording is the exception so far, this does not add consistency at all.

2021-09-13 15:22 UTC, reosarevok commented
> Recording is the exception so far, this does not add consistency at all.

Recording is the only other place where we have the -level-rels implementation, and it supports it on both lookup and browse. Release only supports it on lookup. As such, yes, I'd argue it adds consistency. But I can remove that from the commit message if it's a problem somehow.

2021-09-13 15:24 UTC, reosarevok commented
@yvanzo: Updated the commit message, do let me know if that looks better.

2021-09-13 16:26 UTC, yvanzo approved these changes
Yes, thank you!

2021-09-13 16:44 UTC, merged