MBS-12049: Convert the edit index page to React
metabrainz/musicbrainz-server pull request #2315
Opened 2021-10-26 09:54 UTC by reosarevok

### Implement MBS-12049

On top of https://github.com/metabrainz/musicbrainz-server/pull/2317 since the types are a very big change and it's probably easier to review them as two separate PRs.

2021-11-25 10:47 UTC, reosarevok commented
@brainzbot, retest this please

2021-12-07 17:17 UTC, yvanzo reviewed
You wrote it twice but I cannot understand what exactly means “no current edits use that” and what it does imply.

The added tests seem to be fine.

This pull request should be rebased on `master` to clarify that the three first commits belong to another pull request.

Do you have pointers to help with reviewing the list of edit types in the new `chooseEditDetailsComponent.js` as there is no similar old piece of code in this pull request?

2021-12-07 17:41 UTC, reosarevok commented
> You wrote it twice but I cannot understand what exactly means “no current edits use that” and what it does imply.

Oh. I meant that we have no actual edit types that have a different closing condition (are rejected without votes, or whatnot).

> This pull request should be rebased on master to clarify that the three first commits belong to another pull request.

Done.

> Do you have pointers to help with reviewing the list of edit types in the new `chooseEditDetailsComponent.js` as there is no similar old piece of code in this pull request?

The only way I can tell of is checking each Perl component one by one and seeing what React page they use :( That's how I did it, anyway.

2021-12-07 17:48 UTC, yvanzo commented
> Oh. I meant that we have no actual edit types that have a different closing condition (are rejected without votes, or whatnot).

If I understand correctly these tests were not testing edit’s display but rather that the edit system’s back-end works as expected?

2021-12-07 17:57 UTC, reosarevok commented
They were exclusively testing, for `::Show`, that the page "mentions expire action" and "mentions vote period" (which in reality was not about vote period but the number of votes for early approval). My new version tests actually useful bits, plus those two, but it just doesn't make up an edit type that has a different set of those two options than the default. `::Open` still tests the same things it did (plus more).

2021-12-08 08:50 UTC, reosarevok commented
@brainzbot, retest this please

2021-12-08 16:55 UTC, mwiencek requested changes

2021-12-08 16:55 UTC, mwiencek commented on root/edit/EditIndex.js
> +            <p>{l('An error occurred while loading this edit.')}</p>
I added `die '';` to `sub restore` in an edit class and got this message to show, so that works at least.

2021-12-08 16:55 UTC, mwiencek commented on root/edit/EditIndex.js
> +              <th>{addColon(l('Vote tally'))}</th>
```suggestion
              <th>{addColonText(l('Vote tally'))}</th>
```

2021-12-08 16:55 UTC, mwiencek commented on root/edit/EditIndex.js
> +            edit.is_open && true ? (// server_details.testing_features ? (
This condition looks unfinished.

2021-12-08 17:44 UTC, reosarevok commented on root/edit/EditIndex.js
> +  +edit: {...EditT, +id: number},
This actually is passed to chooseEditDetailsComponent which expects actual EditT, unless we should change that?

2021-12-08 17:49 UTC, mwiencek commented on root/edit/EditIndex.js
> +  +edit: {...EditT, +id: number},
Oh I see, I think we'd have to keep this then, but you can add `$ReadOnly` at least.

2021-12-08 17:55 UTC, reosarevok commented on root/edit/EditIndex.js
> +  +voter?: UnsanitizedEditorT,
It doesn't need to be there at all :) Removed.

2021-12-08 18:08 UTC, mwiencek approved these changes

2022-01-15 17:22 UTC, yvanzo approved these changes
Thoroughly checked `getEditDetailsElement.js` and tested locally with `pink`’s database.

2022-01-15 18:57 UTC, merged