Remove MooseX::ABC
metabrainz/musicbrainz-server pull request #2410
Opened 2022-02-06 20:06 UTC by mwiencek

According to the documentation at https://metacpan.org/pod/MooseX::ABC,

> This module is almost certainly a bad idea. You really want to just be using a role instead!

In most cases we can't easily convert ABC packages into roles, because they extend `MusicBrainz::Server:Edit`, which would also have to become a role.  But then we run into issues where required methods are provided by adjacent roles (triggering compile-time errors), and where attributes can no longer be extended with `+` (common for `data`), which is not possible in a role.

So instead, in most cases I've replaced `required` method lists with stubs that die.  However this means that it's no longer checked that these methods are implemented by the non-abstract classes at compile-time, only at run-time.

This patch incidentally fixes the following warning on plackup start:

> Argument "Moose::Meta::Method=HASH(0x556ed49cc448)" isn't numeric in numeric eq (==) at /home/michael/perl5/lib/perl5/MooseX/ABC/Trait/Class.pm line 61.

2022-02-07 07:44 UTC, reosarevok commented
The cover art changes seem to be failing circleci :)

2022-02-07 17:41 UTC, yvanzo requested changes
It seems sane to drop a dependency which has such note and is unmaintained for 10 years!

> So instead, in most cases I've replaced `required` method lists with stubs that die.  However this means that it's no longer checked that these methods are implemented by the non-abstract classes at compile-time, only at run-time.

Having compile-time checks was the main reason for using ABC I guess.

After fixing Selenium tests, this lack of checks has to be documented.

> This patch incidentally fixes the following warning on plackup start: Argument ...

I’m so used to wait for this warning! :wink: Will have to look for `starting new work` now.

2022-02-07 17:58 UTC, mwiencek commented
Do you mean document it in the code with comments, or somewhere else?  Any suggestions on the best way/place to do that?

2022-02-07 19:26 UTC, yvanzo commented
Good question since it is about code that is not yet written! Even though that cannot replace compile-time checks, there might be two places for documenting this requirement: Comments in classes containing deadly stubs; `HACKING.md`.

2022-02-08 09:12 UTC, reosarevok commented
Is the lack of compile-time checks an issue if we ensure we have proper tests for all of these files?

2022-02-17 18:26 UTC, mwiencek commented
> Is the lack of compile-time checks an issue if we ensure we have proper tests for all of these files?

No, it's not an issue if we have proper test coverage (because the unimplemented methods would die once called).

But I updated the PR with some code comments.

2022-02-17 18:57 UTC, mwiencek commented
@brainzbot test this please

2022-02-18 12:09 UTC, yvanzo approved these changes
@brainzbot retest this please (even though the timeout error seems to be unrelated)

2022-02-18 12:10 UTC, yvanzo commented
@brainzbot retest this please

2022-02-21 07:55 UTC, reosarevok commented
@brainzbot retest this please

2022-02-21 13:30 UTC, merged