MBS-12573: Drop unused degraded column from cdtoc
metabrainz/musicbrainz-server pull request #2667
Opened 2022-09-27 12:34 UTC by reosarevok

### Implement MBS-12573

This was apparently used ages ago to store "a previous algorithm (less accurate) or things imported from freedb that didn't have the accuracy of our ids", said Rob, but "we may have dropped all those back in the day and never nuked the column".
It contains always `FALSE`, at the moment, and we seem to use it exactly nowhere.

2023-05-03 13:43 UTC, yvanzo requested changes
1. The files under `docs/database_schema_diagrams/graphs/` and `docs/database_schema_diagrams/images/` should not be included as this change is breaking `cdtoc` layout and these files have to be regenerated for schema 28 anyway.
2. This is a breaking change for `mbdata` which is used by `sir`. It has to be tracked to ensure updating SIR at the same time as the database schema change.

2023-05-04 15:18 UTC, reosarevok commented
For 1) I dropped the change. For 2) I added SEARCH-706 and started https://github.com/reosarevok/mbdata/tree/schema-change-2023-q2

2023-05-04 17:15 UTC, yvanzo approved these changes
LGTMBDNT

2023-05-08 21:44 UTC, mwiencek approved these changes

2023-05-09 10:03 UTC, merged