MBS-12665: Somewhat widen DNB regex
metabrainz/musicbrainz-server pull request #2686
Opened 2022-10-13 04:51 UTC by reosarevok

### Fix MBS-12665

We took this from Wikidata, but given the valid example added as a test here, it was too strict. Widening it to allow any number, not just 3, as the first digit in the last case.

2023-02-08 15:51 UTC, reosarevok commented
We got the following answer from DNB:

> Jeder bibliografische Metadatensatz und auch Normdatensatz (GND) ist mittels einem Primärschlüssel/Identifier eindeutig zu identifizieren.
> 
> Für bibliografische Metadaten wird der Identifier auch mit den Kürzeln IDN o. PPN benannt, für z. B. CD https://d-nb.info/357016572, lautet der Identifier/PPN/IDN „357016572“. Dieser ist immer enthalten im „Link zu diesem Datensatz“ (Permalink) in der Vollanzeige in unserem Katalog.
> 
> Die Struktur ist wie folgt:
> 
> Protokoll/Schema: https
> 
> Host: [d-nb.info](http://d-nb.info/)
> 
> Identifier: Nummer Identifier des Titeldatensatzes
> 
>  
> Bei Normdaten wird der Primärschlüssel auch GND-Nummer oder GND-ID genannt (z. B. Körperschaft/Musikgruppe https://d-nb.info/gnd/10298370-7 oder Werke https://d-nb.info/gnd/1135594082). Die Struktur enthält daher den Präfix „gnd“:
> 
> Protokoll/Schema: https
> 
> Host: [d-nb.info](http://d-nb.info/)
> 
> Präfix/Pfad: gnd
> 
> Identifier: GND-Nummer des Normdatensatzes

The suggestion from outsidecontext based on this was:

> They basically distinguish between IDs for bibliographic data and "Normdaten" (authority data) from the GND.
> 
> For bibliographic data the link structure is "[https://d-nb.info/{ID}](https://d-nb.info/%7BID%7D)", e.g. this is a CD: https://d-nb.info/357016572 .
> 
> The GND is the "Integrated Authority File" [1], basically a combined catalogue for persons, organizations, works and a few other entities. The GND URLs are always "[https://d-nb.info/gnd/{ID}](https://d-nb.info/gnd/%7BID%7D)". The German Wikipedia has a few more words about the format of the IDs for the GND [2]. Translated by Google Translate:
> 
> Each entity can be clearly identified by at least one identifier (GND-ID). Each identifier consists of the characters 0 to 9, X and a hyphen. An identifier for an entity of entity type p consists of 9 or 10 characters, it always starts with a 1 followed by 8 or 9 digits and ends with a check character 0-9 or X.
> 
> So the characters are limited to [0-9X-]. But above that it looks to me we should not make too many assumptions. It gives the example for entities of type p (persons), so this could be validated more strictly. But besides persons there are 6 other entity types. If we would need to restrict this further the valid formats for each entity type would need to be researched, I'm not sure this is worth it. Maybe it is safe to assume the last character is always [0-9X], the X in general is only allowed at the end and a hyphen can not appear at the start or end. Maybe something like [0-9][0-9-]*[0-9X] is a safe assumption to make.
> 
> The initial example you gave me was http://d-nb.info/97248485X , and with the above example it is clear that this is not a GND ID, so [3] does not even apply here. It belongs to the first category of bibliographic data (which would be mostly for "releases", containing things like CDs, audio books and books). They did not specify a format. But given the example it might be always numerical with X allowed, but that's just a guess. Maybe again we are on the safe side using the simplified regex I gave above (which would also include the hyphen).
> 
> [1] https://en.wikipedia.org/wiki/Integrated_Authority_File
> [2] https://de.wikipedia.org/wiki/Gemeinsame_Normdatei#Entit%C3%A4tsidentifikator
> [3] https://www.wikidata.org/wiki/Property:P227#P1793

2023-02-08 16:06 UTC, PotcFdk commented
> But given the example it might be always numerical with X allowed, but that's just a guess.

Not *always*: https://d-nb.info/998642312
I have not yet seen any bibliographic data id that did not follow the same format as the one specified for GND-IDs, but this is an anecdotal observation.

2023-02-15 19:30 UTC, yvanzo requested changes
Can you explain in commit message why some entity types are still disallowed to link with DNB URLs having either `/gnd` or `/dnbn` as path prefix?

2023-02-15 20:21 UTC, reosarevok commented
Tried to clarify that a bit.

2023-02-15 20:24 UTC, yvanzo approved these changes
Thank you for the summary, it is much more clear now! :boat:

2023-02-15 20:25 UTC, merged