Merge relationship editor changes from the test branch into beta
metabrainz/musicbrainz-server pull request #2817
Opened 2023-01-30 18:40 UTC by mwiencek

# Problem

In order to iterate on feedback from MBS-11847 and other small relationship editor tickets more quickly in preparation for the next beta update, I've been updating the test branch with changes and deploying test.mb so that people can try out the changes.  Now these changes need to be reviewed and synced to the beta branch.

# Solution

Merge the test branch into beta.

This fixes several tickets:
 * MBS-12834
 * MBS-12849
 * MBS-12850
 * MBS-12830

2023-01-30 19:23 UTC, reosarevok commented
@brainzbot, retest this please

2023-01-30 20:14 UTC, reosarevok requested changes
This generally seems good. Please do rescue the help text for dates though (and I guess drop the related commit here since there'll always be something with docs then if the attributes section exists).

2023-01-30 20:14 UTC, reosarevok commented on root/static/scripts/edit/components/HelpIcon.js
> +}: PropsT): React.MixedElement => (
This is just `Tooltip`? Same for at least `BatchCreateWorksButtonPopover` which I cannot leave a comment on for reasons.

2023-01-30 20:14 UTC, reosarevok commented on root/static/scripts/relationship-editor/components/RelationshipDialogContent.js
> +          {hasAttributes ? (
This should probably be reverted if we're adding back the dates help (which we should).

2023-01-30 20:26 UTC, mwiencek commented on root/static/scripts/relationship-editor/components/DialogPreview.js
> +}: PropsT): React.MixedElement => {
I'd probably only use Fragment if the users of the component demanded a fragment somehow (but that's not the case, so it doesn't add any type safety to be overly specific).

2023-01-30 22:50 UTC, kellnerd commented
[MBS-12834](https://tickets.metabrainz.org/browse/MBS-12834) still doesn't appear to be solved for me, the relationship type menu still appears when I'm editing an existing relationship on test.

2023-01-31 01:27 UTC, mwiencek commented
Thanks, it's working in Chromium but I hadn't tested it in Firefox where it appears to be broken still.  I'll take another look at it.

2023-01-31 06:00 UTC, mwiencek commented on root/static/scripts/relationship-editor/components/RelationshipTargetTypeGroups.js
> +            style={sections.length ? null : {width: '160px'}}
It seems to work if I just set `width: 160px;` unconditionally in the .less file.

2023-01-31 06:04 UTC, mwiencek commented
> This generally seems good (and I've played with it in test quite a bit and was happy with it). Please do rescue the help text for dates though (and I guess drop the related commit here since there'll always be something with docs then if the attributes section exists).
> 
> Ideally we can also fix the issue with the double keyboard vs mouse focus on dropdowns before merging (or in a second beta PR after merge).

The date help text has now been resurrected and the double-menu-highlighting has been fixed.

2023-01-31 06:45 UTC, reosarevok commented
5c9ff49607524b55b3984f4e46f3f4bb691c554d is still there though hiding stuff if there's only dates?

2023-01-31 16:44 UTC, mwiencek commented
> https://github.com/metabrainz/musicbrainz-server/commit/5c9ff49607524b55b3984f4e46f3f4bb691c554d is still there though hiding stuff if there's only dates? (and the dates help is not showing for me in test.mb)

Yeah, I must've of screwed up a rebase since the new commit is missing.  Recovered it from the reflog.

2023-01-31 19:39 UTC, reosarevok approved these changes
Tested the latest changes locally and it all feels good to me, and the code also seems sensible. Ship it to beta IMO.

2023-01-31 20:39 UTC, merged