MBS-13094: Allow admins to browse edit note changes
metabrainz/musicbrainz-server pull request #2971
Opened 2023-06-16 15:45 UTC by reosarevok

### Implement MBS-13094

# Problem
Admins should be able to see the edit history for any edit, since otherwise a user could, for example, insult another and then edit the note so that the email is sent but others don't see.

# Solution
This mostly follows what we do for annotations, but most of it does not support translated strings since it's admin-only. Translations are added for stuff that will show in otherwise translated pages.

# Checklist for author
* [ ] Add tests for these pages

# Testing
Manually for now, will add a test next week.

![Screenshot from 2023-06-16 18-44-37](https://github.com/metabrainz/musicbrainz-server/assets/1069224/f5d3ca31-66b8-4497-b2f8-c659384aa5e5)
![Screenshot from 2023-06-16 18-44-15](https://github.com/metabrainz/musicbrainz-server/assets/1069224/23314891-7aba-4c98-8c23-8a96ad4cc393)

2023-06-16 15:54 UTC, reosarevok commented
@brainzbot, retest this please

2023-07-22 10:24 UTC, yvanzo requested changes
Great stuff overall. Code doesn’t embed a single bit of old edit notes in usual edit pages and lists, so no risk at leaking data. Tested locally as admin, non-admin and logged out visitor. Checked CI tests coverage too. Just spotted a very few easy-to-fix points.

2023-07-22 10:24 UTC, yvanzo commented on root/edit_note/EditNoteChange.js
> +          {'Go back to the edit note'}
Edit note change history can be accessed from a list of edits, not necessarily from the edit page itself, so “back” isn’t necessarily correct.

```suggestion
          {'Go to the edit note'}
```

2023-07-22 10:24 UTC, yvanzo commented on root/edit_note/EditNoteHistory.js
> +        {'Go back to the edit note'}
Same as above
```suggestion
        {'Go to the edit note'}
```

2023-07-22 10:24 UTC, yvanzo commented on t/lib/t/MusicBrainz/Server/Controller/EditNote/NoteHistory.pm
> +on who and when can do so.
Probably an oversight here, the description is the same as for `ChangeNote`.
```suggestion
This checks that edit note history can be viewed by admins and only by admins.
```

2023-07-24 19:20 UTC, reosarevok commented on lib/MusicBrainz/Server/Controller/EditNote.pm
> +
If an admin navigated by hand to a page like `/edit-note/20000000/changes`. Given it's admin only, I'll change this to not be translatable, like on another recent PR :)

2023-07-24 20:04 UTC, yvanzo commented on lib/MusicBrainz/Server/Controller/EditNote.pm
> +
Yes

2023-07-24 20:04 UTC, yvanzo approved these changes
:ship:

2023-07-25 05:34 UTC, merged