MBS-13162: Handle Threads links
metabrainz/musicbrainz-server pull request #2981
Opened 2023-07-10 13:47 UTC by reosarevok

### Implement MBS-13162

# Description
This adds `threads.net` (Meta's new Twitter-like) links to the sidebar, and cleans them to use `https://www.` which seems to be the default. It also selects social media.

This patch does not introduce validation yet, since it's unclear exactly what we should allow and block as of now. It also doesn't currently support `streamingfree`, but we might eventually want that since Twitter does it.

# Testing
Added the usual basic URL test.

2023-07-11 11:32 UTC, yvanzo reviewed
Tested with artist for whom this patch indeed selects - as mentioned in the commit message - but also restricts to social network - which is fine but not mentioned.

About recordings, Threads supports videos up to 5 minutes (for example <https://www.threads.net/t/CucwR6erBPo/>) and it doesn’t seem that any other relationship type than `streamingfree` would make sense.

2023-07-12 10:30 UTC, reosarevok commented
I understand the suggestion is we should support posts, which I guess seems sensible enough and closer to what we do with Twitter anyway. Implemented that, see if this seems better now.

2023-07-13 14:46 UTC, yvanzo commented
@brainzbot please retest this.

2023-07-13 14:58 UTC, yvanzo requested changes
The newly added validation makes sense.
Commented on two implementation details.
LGTMBDNT otherwise.

2023-07-13 14:58 UTC, yvanzo commented on root/static/scripts/edit/URLCleanup.js
> +      const isAProfile = /^https:\/\/www\.threads\.net\/(@[^/]+)$/.test(url);
Capturing group is not needed here:
```suggestion
      const isAProfile = /^https:\/\/www\.threads\.net\/@[^/]+$/.test(url);
```

2023-07-13 14:58 UTC, yvanzo commented on root/static/scripts/edit/URLCleanup.js
> +      const isAThread = /^https:\/\/www\.threads\.net\/t\/[\w\d]+?$/.test(url);
1. The quantifier `?` is not wanted here as the thread identifier is mandatory.
2. The expression would not work with thread identifier containing a hyphen `-`.
   Maybe just use the same expression as above?
```suggestion
      const isAThread = /^https:\/\/www\.threads\.net\/t\/[^/]+$/.test(url);
```

2023-07-14 10:31 UTC, yvanzo approved these changes

2023-07-14 10:37 UTC, merged