MBS-13284: Don't require edit note for alias removals
metabrainz/musicbrainz-server pull request #3047
Opened 2023-09-27 06:26 UTC by reosarevok

### Implement MBS-13284

# Problem
This was originally added on my request over 10 years ago, but while it makes sense to require a note for all entity removals and other similarly destructive edits, alias removals just drop an MBID-less text field that is trivial to re-add, and is not significantly different from dropping a disambiguation or other similar text field.

# Solution
Just drop the `requires_edit_note` argument from `delete_alias`.

# Testing
Amusingly, we had more tests checking for this edit note requirement than most other more important ones...
I removed most, but left one testing it's no longer required.

2023-11-16 05:15 UTC, mwiencek commented
I still see some code in the tests like:
```Perl
                    'confirm.edit_note' =>
                        q(Some edit note since it's required)
```
which can probably be removed (indirectly testing that an edit note is not required) or at the very least re-worded.

2023-11-16 13:08 UTC, yvanzo requested changes
See the above comment. LGTMBDNT otherwise!

2023-11-16 19:19 UTC, reosarevok commented
Updated these.

2023-11-16 19:44 UTC, mwiencek approved these changes

2023-11-20 10:42 UTC, yvanzo approved these changes
Thank you! :ship:

2023-11-20 15:23 UTC, merged