MBS-13326: Add documentation bubble for the artist sort name field
metabrainz/musicbrainz-server pull request #3081
Opened 2023-11-07 08:46 UTC by reosarevok

### Implement MBS-13326

# Problem
"Sort name" is a non-obvious field. Recently we've seen people reading it as "short name", but even without that, it's often filled wrong.

# Solution
There seems to be entirely no downsides to adding a bubble with a short explanation and a link to the guidelines, so I'm doing that and hoping it's enough to clarify the usage.

# Testing
Manually, just to make sure the bubble appears and goes away as expected.

2023-11-07 20:19 UTC, reosarevok commented
I like the wording, so updated the PR / image.

2023-11-10 21:45 UTC, loucasal commented
I think the example line was meant to read "Last Name, First Name" rather than the other way around.

2023-11-16 05:11 UTC, mwiencek requested changes

2023-11-16 05:11 UTC, mwiencek commented on root/components/forms.tt
> +      <p>[% l('Last Name, First Name” and “Group, The” are common examples of sort names.') %]</p>
```suggestion
      <p>[% l('“Last Name, First Name” and “Group, The” are common examples of sort names.') %]</p>
```

2023-11-16 20:10 UTC, mwiencek approved these changes

2023-11-16 20:11 UTC, merged