Store instrument_aliases on LinkAttributeType
metabrainz/musicbrainz-server pull request #3097
Opened 2023-11-17 12:51 UTC by mwiencek

Cherry-picked from https://github.com/metabrainz/musicbrainz-server/pull/3093.

Instrument aliases are needed to implement MBS-13367. Since this changes the format of cached data, it needs to be deployed on both the production and beta servers at the same time.

2023-11-17 14:04 UTC, mwiencek commented
@brainzbot test this please

2023-11-17 14:30 UTC, mwiencek commented
@brainzbot test this please

2023-11-17 17:02 UTC, mwiencek commented
@brainzbot test this please

2023-11-20 10:22 UTC, yvanzo requested changes
Does it resolve any of the tickets being addressed by the original pull request? If not, what does it address? Has it been tested and how?

Please clarify all of these using our [pull request template](https://raw.githubusercontent.com/metabrainz/musicbrainz-server/master/.github/PULL_REQUEST_TEMPLATE.md) and in commit message.
Having a separate ticket (even if a sub-task of an existing ticket) would probably be helpful too.

2023-11-20 13:35 UTC, mwiencek commented
Meant to set this as a draft while I look into the Selenium failure.

@brainzbot test this please

2023-11-20 17:26 UTC, mwiencek commented
@brainzbot test this please

2023-11-20 19:58 UTC, mwiencek commented
> Does it resolve any of the tickets being addressed by the original pull request? If not, what does it address? Has it been tested and how?
>
> Please clarify all of these using our [pull request template](https://raw.githubusercontent.com/metabrainz/musicbrainz-server/master/.github/PULL_REQUEST_TEMPLATE.md) and in commit message.
>
> Having a separate ticket (even if a sub-task of an existing ticket) would probably be helpful too.

Updated the PR description to hopefully clarify things.

This is a small part of [MBS-13367](https://tickets.metabrainz.org/browse/MBS-13367) and is an internal-only change, but as it affects cached data it needs to be deployed to production first as production and  beta share a cache.

2023-11-20 20:32 UTC, yvanzo reviewed
Thanks for the added ticket and details.

Nitpicking: It seems to _load_ data rather than to _store_ anything.

Didn’t find how to test that but probably found an oversight still.

2023-11-20 20:32 UTC, yvanzo commented on lib/MusicBrainz/Server/Entity/LinkAttributeType.pm
> +        $self->instrument_aliases ? (instrument_aliases => $self->instrument_aliases) : (),
I didn’t test but it seems to be missing:
```suggestion
        $self->instrument_aliases ? (instrument_aliases => to_json_array($self->instrument_aliases)) : (),
```

2023-11-20 20:36 UTC, mwiencek commented
> Nitpicking: It seems to load data rather than to store anything.

Well, both I guess. :) It loads it from the database, and stores it on the Moose objects, which are stored in Redis.

2023-11-20 20:38 UTC, yvanzo commented
Yes, in a way, but the longer term storage is the database, it made me look in the wrong direction.

2023-11-20 23:40 UTC, mwiencek commented
> Yes, in a way, but the longer term storage is the database, it made me look in the wrong direction.

Did `s/store/load/g`. Also, I now invalidate the `link_attribute_type:all` cache when instrument aliases are modified.

2023-11-21 07:45 UTC, yvanzo approved these changes
LGTM and the added CI tests too. Thanks a lot! :ship:

2023-11-21 16:01 UTC, merged